### ISSUE TITLE
New v.3.0 Update Crash

### ISSUE THREAD

**Issue by TomahawkStrikerz** [Wynd/MineMineNoMi3#10]
The new update makes the game crash when an enchanted item is used against any entity. I made a Sharpness 2 Diamond Sword and used it against a Zombie and it crashed my game. I tested out a little more to see why and any enchanted item used to attack any mob will crash game. Please fix, please!

Sincerely,
TomahawkStrikerz (big fan)

**Comment by TomahawkStrikerz** [comment]
Also, I did test to remove any other mods to see if it was any of them tampering with the crash but it only came out to be the Mine Mine no Mi mod to have been the issue.

**Comment by Wynd** [comment]
Hi,

Thanks a lot for the detailed feedback..this however is a known bug and it was already fixed for the upcoming version.
(also as a side note..when talking about crashes please add a crashlog as well...even if the crash is obviously because of the enchantment the actual source of the bug might be different, in your .minecraft folder there should be a crash-reports folder, just copy paste the latest log on pastebin or other similar website and post a link)

Thanks again 😃
