### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by TheBakersMen** [Wynd/MineMineNoMi3#101]
A few quality of life suggestions:
- Allow commands to be called by the server, meaning when used in conjunction with customnpcs, the commands called by quests don't work (yes I messed with the op-permissions in the config and still nothing). I think commands are only usable by players is the issue.

- A config option to change the doriki rate you gain from killing mobs. I'm sure you want the mod to make the game difficult, but I play a custom world with myself and a few friends; we don't have much time to grind doriki for 10+ hours, and we don't want to cheat with commands.

Also I know it's already planned but I'm looking forward to the kairoseki enchantment on weapons being fully implemented.

Thanks for your hard work :)

**Comment by Wynd** [comment]
It's a bit late now to implement those in 0.5.1 but I'll try, I like the doriki rate idea and since we already have a few "rate" based commands I don't see why not, you also made a very good point with it so I'm all for it.

As for the first issue...I am not familiar with how command blocks (or customNPCs for that matter) work exactly...so we'll see, as I wanna fix this as well

**Comment by Wynd** [comment]
Fixed the first bug and added the new option in the config. Closing as fixed.
