### ISSUE TITLE
Questions and Problems

### ISSUE THREAD

**Issue by Ryanfmr** [Wynd/MineMineNoMi3#11]
This isn't about crashes but some questions and problems i've encountered with the mod(I've tested all these all these things in 0.3.0 and they all still apply) but first of wanted to thank you making and working on this awesome mod that i've been enjoying for about I think it's been between 1 and a half and 2 years now maybe a even a bit more. Now on to the questions first would it be possible for you to make a list with a description of what every (Devilfruit) ability or certain items does? Most are fun too figure out on your own in my opinion however with abilities like karakusagawara seiken (which as far as I know only hurts hostile creatures) or the Kage Kage no Mi fruit(specifically the part on how to actually use shadows) i still ain't sure on what they exactly do or how they exactly work. Now with the "problems" part out of the way I have some suggestions /question. Firstly do you plan to add Zoan fruits back in the game and give them more abilities and what not? If yes I don't know if this is possibly but I think it'd be very cool to make a template or something so people can design there own skins or maybe even let them use custom models for the Zoans they are using. I'm specifically asking about this because I think I've seen people on the forum that aren't a fan(this is including myself) of looking like someone from the anime instead of how your character would look like if he/she's transformed. Secondly and this is very specific would you be able to make it so that the duration of the barriers that spawn when using Bari Bari no Mi are configurable to last longer? And lastly is there a way  to get rid of a eaten Devil fruit like drinking milk did and in 0.2.4 and before(except deleting the playerdata). I'm aware of issues like the low ship spawn rate in 0.3.0 and know this will be fixed in the next release but I feel like the issues above are either very personal or not brought up on the forum. And finally i wanted to say thank you for reading this and for working on the mod I hope you appreciate the feedback and don't take offense to any of this.

With appreciation,

Ryanfmr.

**Comment by Wynd** [comment]
Hi,

Thanks for the feedback, why would anybody be offended by this ^^ some of these problems will be fixed/implemented in the next update (0.3.1) which will be released really soon..but here are some ideas about the next update :
- For the DF/Ability descriptions we're working on a wiki-like page that will answer such questions
- Zoans will also be added but they'll still be WIP and as such certain problems will still be present 
- The textures were also improved and now they're more generic..instead of looking like the actual characters...(you can always change the texture if you want to customize that) but...I'm not so sure about adding custom models using a _friendly_ API, the problem here is that animations would not work at all 
 due to how the new system works...since the mod is open-source you can grab it and change the model and use it on your server or single player.
- Right now no you cannot remove the DF without /kill ..in 0.3.1 there will be a /removedf command

**Comment by Ryanfmr** [comment]
Hello Wynd,

Thanks for the response looking forward to 0.3.1 even more then before now! I know life can get in the way of things but when are you expecting to be able to drop 0.3.1? And you probably have people for this but if you ever are in need of additional testers I'd be more then willing to help out.

Thanks and have a good day.

**Comment by jarekszzz** [comment]
Hi Wynd,

How can I change ratio of spawning pirate/marine ships? I don't have much time to play, so I don't want to play for, like, 9-10 hours to find one ship and I don't want to chop millions of trees to get a devil fruit.

Thanks.

**Comment by Wynd** [comment]
@Ryanfmr not sure tbh...like you've said life can (and usually will) get in the way...but I will announce it 1 week prior in the #announcements channel on discord and on forums
@jarekszzz right now there is no way for that...0.3.1 will add config options for a lot of other things including those that you've mentioned

**Comment by PZHub** [comment]
Hello Wynd,

I think it would be very cool that depending on your doriki your damage and the power of your devil fruit (ice age range, explosion range and damage, damage) would be bigger, I don't think it's hard to make.
By the way, I think that there should be a fruit to remove your devil fruit so players can remove their devil fruit without dying or using commands.
Also you should make that you can only use gear 4 if you have haki. Also it would be better if your fists when using gomu gomu no pistol/bazooka are black only when you are using the haki ability.

**Comment by Kenryuu** [comment]
Hello PZHub,

As someone that really care about balance, I do not find this idea (with all my concern) very healthy for the game. Doriki grant already a lot of power, and amplifying the power gap between people is not something we want, because it'd make essentially experimented users godlike.

**Comment by PZHub** [comment]
Then what about it beeign optional? an option that can be turned on or off from the config file.
I think the power gap will be good for roleplaying battles, like the ones we have seen before performed by End Team. The fights already looked good, but if we see a fight between people like yonkou or devil fruit users with enough power to destroy mountains and we get attacks that can barely destroy a house, It wouldn't look very realistic. 
I agree with you about it beeign unbalanced, but as I said before, it wouldn't be bad if it was configurable.

**Comment by Wynd** [comment]
Doriki progression won't affect the damage scaling...like Ken said we want to focus more on actual skill rather than high numbers...adding an option for doriki scaling might become a thing in the near future I won't say no...but it's definitely not a high priority right now..
For gear4...I agree with you and that's how it was supposed to be..however the current system has a limitation and you cannot use 2 passive abilities at the same time (also used to avoid spamming things like tekkai + sora...) so that'll be impossible to do right now...

Also gonna close this thread because I don't want this to become a general suggestion post...Most of the things mentioned by op are already implemented in 0.3.2 and others are registered for future updates.
