### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Yakend** [Wynd/MineMineNoMi3#24]
Okay, so you should make a skill tree, so, currently for humans roku shiki is what you get, I think you should have to go to the marines or someone in cp9 or maybe a dirty marine that will teach you for a price if you are a pirate, or you could go to the revolutionary army and learn sabos moves from him, or different nps that will teach you different things that will unlock seperate skill trees ALSO PLEASE PLEASE MOST IMPORTANTLY, make it so you can use keybinds like ctrl+1 and ctrl+shift+1 and stuff like that PLEASE
I think maybe when you spawn in you get an item kind of like in the minecraft comes alive mod, where it spawns a villages, just instead it generates different structures depending on the item you use and said structures cannot be spawned in a certain radius of eachother also in the create a world section you should add one piece world and one piece story world, with the worlds being identical but one piece story world has npcs with a waypoint and map system showing you where to go to the next npc to do the story, regardless of the world, it should be a fairly accuratly sized one piece world, with fairly accurate places, of course this world type would essentially be a big one piece map, but the difference is you should code it so that if u get to the end of the world the start will generate again or well, not generate but maybe a giant blue barrier will be their that will teleport you back to the start would be easier, also you should have inside these worlds specific areas where one piece riff raff mobs will spawn like random pirates or at marine bases marines will spawn. also if you try to go past an island to early without beating the boss of the previous island it will say you have not beaten the boss, go back with a button saying (click here if this is a bug) which will let them continue anyway and if they have killed the boss but their doriki is low it should say when they try to continue "Your level is low, are you sure you want to continue?"
For if you choose marine instead of pirate
it should be monotonous grinding at random boring places where you get sent by the marines to go take down pirates until you get higher rank where you can eventually join G5 in the new world and with enough grinding become a navy admiral or even fleet admiral.
For fishmen, so it isnt unbalanced start them in the east blue aswell, make sure that people will naturally run away from them and they cannot choose marine, also marines should attack them for no reason as well fishmen should have a natural skill tree, like teeth bite that just adds on to their punching abilites and different things like that that make them faster, more durable and other things, you should also add similar just faster,more durable and stronger parts of skill tree for the other races as well

I know this is a lot, and i know development must be hard, but please do keep these in mind as projects to slowly work towards when you get the time, i think these things would make the mod the actual best anime mod NIGH the BEST MOD ever, thank you for the time of reading, sorry for spelling mistakes or if its hard to read 👍 

EDIT: when i say keybinds i am talking about for the abilites how they are naturally bound to 1-9 where i think you should be able to also right click an ability and an option saying CUSTOM BINDING should pop up where you can bind it to what ever you want, but can still only use it in combat mode

**Comment by Wynd** [comment]
Morning...you must be new around here...first of all next time try to format your post using bullet points or clearly defined paragraphs...I'm a pretty patient guy and don't mind reading this much...but other won't be like this and will simply ignore a huge wall of text such as this.
Another thing...please be aware that this is a minecraft mod at the end of the day...and as such I'm _very_ limited in what I can add or change...

Again..you must be new around because I explicitly stated many time that the mod won't ever have a skill tree or any generic leveling system, some progression will be available soon and it'll get expended in future updates as well but not with stats or levels or skill trees.

About the Ctrl + (shift) + something...minecraft doesn't really allow multiple keys for keybinds by default...it's on the list but not with a high importance right now, for now you'll have to deal with just changing the keybinds to single keys (I believe additional mouse buttons work as well tho so you can try that, but right/left click are hard coded as for minecraft so no chance there..)

For the story/world generation thingy...you have to understand I'm doing this solo (at least coding-wise), and certain things are by default super hard to add normally...doing a story mode will be pointless imo since I want this mod to be fully integrated within a normal minecraft world and act as an adventure mod rather than a full conversion mod...an item that spawn structures is also pointless and kind of a cheat as well..all the structures are spawning normally in the world and require some exploration to do so (one of the main things I want to improve) 

I appreciate the entire post and the fact that you took time to write it (and don't worry about grammar that much we don't care about around here), but other than the multiple keys being bindable I'm gonna have to say no to everything else, there's way too much stuff and most of it doesn't really cover what this mod is trying to achieve, there are some features in the new version however that will probably be similar to some things that you've mentioned and I will try to take notes from it and expand this new feature in the future.

**Comment by Wynd** [comment]
Honestly if you really wanna learn how to code, modding is the best (easiest + imho funniest) way to learn coding..but yes playing and feedback are always welcomed ^^ the discord server is also there so if you wanna hop in and chat with others feel free to do so.

Ok now I understand better...I'm not really a huge fan of items anymore (obvious by the current changes xD) I could probably add a command for those although I'm not sure how certain elements (like spawners or loot chests) will be handled...but I'll see

Yes most definitely more structures will be implemented and navy bases (not really _the_ HQ) will be implemented...along with some other fun activities surrounding them, you could say that structures (especially interesting ones) are a priority of mine but just having random structures around the world will get boring after a while (kinda like no one talks about the vanilla jungle temples anymore...) so there's a new feature in the next update that will over the time wrap around structures and mobs and offer more things to do than just raiding these.

I'm kinda of an oddball of the society in that I just say whatever I think or feel straight without beating the around the bush...with the idea that humans needs to stop being so sensible and feel attacked by anything. So thanks ;3 

If you're talking about the DF Awakenings...that's a really touchy subject even among us, the devs...ultimately we've decided to keep them on hold until more information will be shown about it...we really don't know anything about this other than what Doffy said. (of course if I'll ever  be out of ideas I'll just add more awakening-based abilities and call it a day 😁 )

**Comment by Yakend** [comment]
Okay, I understand fully and I will talk in the discord chat when I find a chance to, you have genuinely now got me interested in coding mods, the best I have ever done is just using a mod maker thingo, that I did no coding in that mostly failed, but now, I am going to actually to look into the coding aspect of things.
As for awakenings, that is COMPLETELY understandable, also as for the /doriki command, you should add that to the normal command list, because it doesn't show up for me if I press tab

**Comment by Wynd** [comment]
Don't use mod makers...ever...anyway what do you mean "command list" or "press tab" ?....Think I'm missing a thing about vanilla minecraft here >.>

**Comment by Yakend** [comment]
oh haha, in minecraft with commands you can press the command button "/" then the tab button to bring up all commands, if u type the first letter of the command you want, for example gamemode you would do /g then press tab and most likely gamerule will pop up, press it again then gamemode will pop up, doriki does not do this for me which makes people not realise that it is a command if they didnt see it on the discord

**Comment by Wynd** [comment]
Some of these suggestions were implemented in the latest version ([changelog can be found here](http://pixelatedw.xyz/changelog)) as such I will close this issue, (for the few ones that were not added right now, they've been added to the to do list and will most likely be implemented soon
