### ISSUE TITLE
Yet Another Suggestion 

### ISSUE THREAD

**Issue by Mind101** [Wynd/MineMineNoMi3#39]
So I have a list of suggestions for you Wynd, this might be a bit long but I'll keep it organized so you don't have to read a wall of text. 

- Make people who eat the Gomu Gomu no mi not get hurt as bad by a non haki user, a normal person with no abilities. Pretty much, make the damage rate it takes from normal hits to a 0.5, which means that instead of a person dealing 1 heart per hit it will usually be a half heart. This also affects other devil fruits abilities when they hit someone who ate the gomu gomu no mi, I guess it's some sort of "resistance" effect in a way. 

- When someone without haki hits a logia, little particle effects come out of the logia user. This might help you identify which logia the person is, for example... when you hit someone with the magma fruit, the effect that the magma fruit creates will sparkle off of the person, this will make servers interesting because you could prepare a counter for the fruit, like water or lava and you hit them once to identify which logia they are and once you fight them... well... They might stay alive for a while longer. 

- Make it so Rokushiki and Haki aren't in the same plane... It's really annoying when you want Haki or Rokushiki alone and you just get both once your doriki is high... It just fills your action inventory. It's annoying for me but there should be certain specific ways to get each one of them. Here are some suggestions for those types of ways...

Busoshoku Haki - Well for this one... you just punch things. But it's not so easy to get this power just by punching. You need to punch mobs, it doesn't work on passive mobs. Pretty much... the more mobs you punch the higher your damage you do with your fists gets, once it gets to a certain point you will get Busoshoku Haki, People usually use swords in this mod anyway so this adds a brand new twists, it makes it harder too because to kill your average mob you have to bunch them atleast 10 or 20 times, this will be harder at the start, also... once you get to a certain high level of punching the lower ranked mobs like zombies won't increase it, you'll have to move on to higher mobs, (mobs from the mod or smth) 

Kenbunshoku Haki - Well for this once you will have to craft a blindfold, 3 leather or whatever the recipe will be. You pretty much put it on your helmet slot and this will either... cover your whole screen or give you a blindness effect. Pretty much, you have to wear this as you travel through the world, it won't do anything if you just stand still in the same place. This is very challenging since... well... you can't see. Once you've had the blindfold long enough and traveled alot you will start to see the enemies... they will start to glow. Leave it on longer and you'll develop a new special skill... Foresight, it's really simple really... theres a chance to not take any damage for an attack, the chance increases the bigger your Kenbunshoku haki is, getting it to 100% has to be extremely hard. 

Haoshoku Haki - This one... not many people are going to have it. Pretty much if you're low on health and you're almost going to die and you're at one heart, there is a 2% chance that you might awaken your emperor's haki, it will say so in the chat. After that you just play normally until it happens again, it has to happen 2 times. After that you can get it by talking to Rayleigh, a passive entity that spawns randomly in the world, you fight him and an elephant and he will teach you the Emperor's haki, the more you use it the stronger it gets, obviously a cooldown will be set, 3 minecraft days sounds good. If you have it maxed out then you can even affect strong mobs with it. The range also increases. Also, if you ever add huge animals from one piece, make it so they become your ally if you use it on them. 

- Adding Zeni and making Zeni useful, so pretty much... add 5 merchants in every single village, one that sells armor, another that sells swords, Another that sells food, one that sells guns, and one that sells mechanical parts (for the robot people to build)... 

-  So in the mod, bounty isn't such a huge thing... it doesn't benefit you in any way. However, if you raise your bounty to a certain number more marines will spawn near you

- Next, A new race, the Giants... pretty self explanatory. You can be a giant, the damage you do with your fists is about 4 when you start. 

- Make the Ushi Ushi no mi transformations bigger...

- Also, add a way to have more resistance to attacks, or add a way to increase your hearts... It'll be lame if you fight someone and you kill them immediately with your df even if they're strong. 

I guess thats it.

**Comment by Wynd** [comment]
For most suggestion we'll see...since they're here, I'll talk with FG over them and see what's ok and what's already in the list, I have however some personal comments that I wanna address :

- The logia particles are already a thing since 0.4.0 and it pretty much works as you've described nothing more to add here
- Zeni is in DBZ as far as I remember xD we have Belly here
- Indeed bounty isn't that useful right now and we have plans to make it even more useful in the future updates in both SP and MP, one thing is actually what you've suggested.
- For the Giant race and bigger transformation points I've already explained in the discord why these cannot be done at the moment so here's the message, the problem is the hitbox of the player : 
![image](https://user-images.githubusercontent.com/6152557/48916196-087b5c80-ee8a-11e8-9299-782c2237c0a2.png)

**Comment by FGpisces** [comment]
Hi, so as Wynd said, some of these things are already planned, and I'll try to give a more detailed answer.

- Althogh a quite suggested feature, the resistance against "blunt" attacks can't be added to the mod for several reasons: 
as a punch does 1 damage, meaning half a heart, it wouldn't be possible to further split the damage into two; 
it wouldn't be possible for weapons to assign categories to which is a blunt weapon, so they would still do normal damage; 
lastly, this could definitely not affect DF abilities, since it has been proven that DFs are effective against other DFs, the only exceptions being that Gomu is immune to Goro attacks
for these reasons, the "resistance" of Gomu is only implemented as taking no falling damage
- As Wynd said, the Logia particles are already an implemented feature.
- We do plan to make more ways to obtain haki, the blindfold being a very suggested way of obtaining Ken haki, so that will probably get added.
- As for Busoshoku haki, the problem is that Doriki is the overall way of measuring your strength, so adding the way of having to just punch mobs would be annoying, because we don't want to limit the players to just do a specific action a large number of times. Of course, there will be other ways to obtain Haki, we just have to make them more appealing and less repetitive.
- I won't say much about Hao haki, as the way it will work should be a mystery even for the players to figure out, but we'll note your idea.
- Bounty will be a currency to use with many merchants, be it on boats, in bars, or random travellers.
- Lastly, you get more hearts with more doriki, that is already an implemented feature, you can reach 100 hp, so 50 hearts.

Thank you for your suggestions, I hope I answered everything. Keep looking forward to the new updates ;)
