### ISSUE TITLE
Yet another Suggestion part 2

### ISSUE THREAD

**Issue by Mind101** [Wynd/MineMineNoMi3#43]
I'll just get right into it...

- When you have normal haki it's just... well... normal haki... nothing special. But if you have really high haki and you use busoshoku haki, a bunch of purple particle effects go around your fist... This makes it so people know you're a master haki user. 

- Make a system for Emperor's Haki... where if one player/mob has 100 less willpower or doriki than you then they get knocked out but if they're on par with you then you'll just clash... maybe add an effect for when 2 emperor's haki are activated in the same place.

- I know you're trying to find a way to make this work... but make Busoshoku haki visible for players. 

- Make the range for sensing people with Kenbunshoku Haki larger... when I sense someone its usually when we're like 6 blocks apart... Also it would be great if the glowing aura to sense people was added back... then again its 1.7.10 so I don't know. 

- For Gura Gura no mi make it so It isn't just an explosion... make it seem like its actually an earthquake thats being created. Kinda like this... maybe more destructive than this, maybe x10 it a bit. :p 
https://media.giphy.com/media/XKGvucpLzwFAV4exXs/giphy.gif

- Just like the sword master make is so theres a master for Fishman Karate, Koala knew fishmen Karate and she was pretty much a human... But when you meet the guy, if you have a devil fruit then he won't teach you anything, that makes sense because the main basis of Fishmen Karate is... well... water. 

- Add a way to get devil fruit abilities instead of automatically getting them once you eat a fruit, like you have to use a primary ability a lot to get another ability... Example: when you eat The Gomu Gomu no mi you only get Gomu Gomu no Pistol, if you use Pistol like 15 times then you'll learn gattling, if you climb a tall cliff and fall down then you'll learn Gomu rocket... this is a terrible example but I hope you know what I mean. 

- Non signature move abilities... what I mean by this is... abilities that the person with the fruit in the show didn't make... other uses for the fruit. Maybe some passive abilities, abilities that help survival... not all just fighting. Then you can use those abilities that help survival in a unique manner like the character in the show with the df would do and use it cleverly in battle. Weird suggestion but ok. 

- Make it so if you enable haki and use Gomu gomu no mi abilities, you use the abilities with haki... I'm sure this has been suggested alot. But I included it anyways. 

- Question: Will you add the Neko Neko no mi Model: Cheetah? It's a filler fruit but its a cool zoan fruit still. 

- Another question: Will the swords be 3d models at some point?

- Make it so you can add Haki to devil fruit powers... not just Gomu gomu no mi... Just get a little creative and see how haki could be embedded to other fruits. 

- Add Ito Ito no Mi's awakening, you have to use every ability it has 50 times in order to get it, and I know that won't be so easy. Maybe make it so the floor turns into string and it expands for at least 50 blocks around you, and it traps anyone that is in its way. 

- Maybe add more clothes? I wanna be looking badass when I beat some marines. 

- Make it a 3% chance that a logia user will not get hurt by a haki punch, Its like what Aokiji did against whitebeard, he made a hole on his body so that the haki can pass through and not harm him. 

- Question: Will more animations be added to fruit abilities? 

- Make it so you can add Kairoseki to normal swords, the sword will have a black spot on it and stuff... kinda like a modifier, it's very limited tho, you're only allowed 5 hits and the kairoseki breaks. For those people who don't have haki yet... 

- Make a sparring partner mob that you can spar with... pretty much you level up your doriki with him, he gets stronger and stronger as your doriki increases, he gets knocked out but you can choose to kill him. You find him randomly in a village and you pay him berries and he just follows you around and tries to make you stronger, hes an alternative to people tired of killing mobs all the time. 

- Make it so you can increase each haki in a certain way, you can choose to level up one more than the other and the difference between a weak version of haki and a stronger one is huge... Like if you wanna level up just your observation haki and get it high enough you will be able to sense things further than before. 

- Black leg style... should be a skill, kinda like swordsmen and medic and stuff... It can be really fun, launching yourself to the opponent and kicking him upwards and if you have haki you can have more fun with fire. The possibilities could be endless. It would be even better with kicking animations too. 

- Attention to small detail, strong abilities should have shockwaves, so you feel powerful... like the blocks around you fly around, similar to the Gura Gura no mi gif I showed you but a smaller version. 

- Now the Kage Kage no mi... this one could be difficult to implement but I don't know. Let's say you have the Kage Kage no mi and you meet a creeper, you can steal his shadow and if you meet another mob or player you can put the shadow in his body and he will act like a creeper, get close to him and he blows up and dies, unless the guy has a lot of health, the explosion for him would do the same damage as what a creeper would do to you. This fruit only works on vanilla mobs, I see it impossible working with other mobs from other mods. Obviously theres a cooldown for this, it's really powerful ability and can be used with creativity. 

- More attention to detail... When you're about to use an ability that requires you to punch someone, when you enable it and the icon is green... the effect of that ability will be on your hand, like if you were to punch someone with the Gura Gura no mi ability then there will be those little cracks on your fist, that way people in multiplayer know what's coming and have time to dodge... singleplayer aswell, its just overall a cool addition. 

- Make it so some strong abilities stop projectiles, like if you use the Gura Gura no Mi's abilities, just the pressure from it should stop projectiles from coming at you. 

- Maybe if you can... make it so Gomu abilities actually look like stretching instead of a fist flying at someone, and make gear 2nd infused abilities much more faster than the normal ones, there should be a difference. 

**Spoiler Alert**
- Kaido's fruit... we don't know much about it as of 11/30/18 but we all know that it turns you into a giant dragon which is fucking dope, when is that coming to the mod? like it should be in the next update or smth, its too great. 
**Spoiler End**'

- I'm asking for the impossible here but it would be great if we could have ships for us to ride, and other ships can shoot at your ship. 

- Would be great if the abilities for your swords got bigger and stronger if you enabled Haki on your sword, would make haki much more worthwhile. 

- Maybe add a escape ability for all logias, your character breaks and turns into the element you are, it gives you a speed boost and you literally become your element... like if you're lightning you can just teleport out by turning into lightning itself. I hope I'm making sense. 

- Last and Final thing/question: As of now it's 0.4.1, will there be new fruits in the next update?

**Comment by FGpisces** [comment]
Hi, as last time, I will try to answer all (or most) of these suggestions.
- advanced Haki is planned and will get added in the future, with more creative ways to get it.

- Haoshoku Haki is also already planned with a pretty nice system, but the effects idea is cool.

- Yes, Wynd is trying to figure out a way to make other people see buso haki.

- Ken haki will be changed a bbit with a new configuration for it, and since the mod will also get updated to 1.13 once the forge is out, the glowing effect will get added.

- I don't know how hard it would be to code, but it looks awesome and definitely a great idea.

- The race techniques will remain only to their races for now, and masters will only teach techniques like the sword techniques, and for snipers and medics later on (soon hopefully).

- We decided that DF abilities will never have a leveling, or progression system, that the user will always get all of the abilities.

- We are already trying it with some fruits, but making abilities not based on what we see in the anime/manga just seems unnecessary at the moment, as we don't know what things the abilities are fully capable of, we don't have any reference material, and (not that we aren't creative), we definitely first want to focus on what IS in the anime/manga.

- Of course, we will try to make it so that if youu acticate haki, all your abilities will have haki as well.

- We'll try to eventually add every DF, even non-canon (except theatre-play DFs).

- Most likely, we'll try to add it, but I can't say for sure when.

- We decided to not add awakening yet, since we only know of 2 (or 3) DFs that have it, and since only Ito is in the mod, it would get too op. Also, we nned to think of a nice way to incorporate it, since we're against a DF leveling system.

- More clothes will definitely be added in the future, don't worry ;)

- Since we don't really know much about why Akainu didn't get hurt there, and Logias are already pretty op (and since haki is pretty difficult to get), we won't be adding this.

- Don't know what you mean by animations, but there will definitely be more custom particle effects.

- Kairoseki will be an enchantment for weapons in the future, and will allow the user to hit Logias.

- The sparring partner is a nice idea, we will look into it :)

- More fighting styles will get added later, but right now, Wynd needs to find a nice way to animate the player model, since we actually want to see the "kick".

- As I said before, no idea how hard it would be to code flying blocks, but we'll obviously try.

- Nice idea :) we already have new improvements planned for Kage, and we'll definitely try to add this.

- This will obviously get added, but it's the same problem currently as with buso haki, others not being able to see it.

- Also a very nice idea, will try to implement it.

- Like already said, changing the player model in such a way is very difficult (and nearly impossible if you aren't iChun), but Wynd will just need to become a god and just do it.

- Kaido's DF will take a VERY long time to be in the mod, since before adding any DFs, we wait till they're shown in the anime, and till the full arc is over.

- Ships to ride is a very suggested feature and we'll try to add it.

- As stated already, we'll try to incorporata haki in all abilities.

- Teleportation for Goro is planned, and we'll  look into how people can "turn into their element".

- Finally, YES, the next update (0.5.0) is officially the Devil fruit Update

**Comment by MXlordsMapone123** [comment]
fg can you tell me which fruits will be in the new update?

**Comment by FGpisces** [comment]
Nope, I'm sorry, the new DFs are a secret.

**Comment by LucasMeierTurtor** [comment]
Hola me gustaria hacer una recomendación para el mod
me gustaria que agreguen un sistema de amigo donde podamos jugar en multijugador sin preocuparnos por matar al que tenemos de amigo
hacer que los efectos provenientes de la fruta del diablo de nuestro amigo no afecten en nada!
