### ISSUE TITLE
Can't get swordsman's abilities

### ISSUE THREAD

**Issue by SteptimusHeap** [Wynd/MineMineNoMi3#47]
**Describe the bug**
Swordsman abilties aren't being given. Have max doriki. Have quest progression and quests on
**To Reproduce**
I did the swordsman's quests, got no abilties
I did use "/time add 1000" until I got 100% to finish the night quest. 
I do have a devil fruit. Using the Tori Tori No mi

It should give me the abilities right? I didn't get any

**Comment by FGpisces** [comment]
The problem is, that the current quests aren't a finished quest line, we plan to add a lot more quests, which will give you abilities. For that reason, the default config is " B:"Allow Quest Progression"=false ", because the current quests only give you the first ability. You can still finish the quests, they just won't give you any new abilities, so set the config to the default value to get them.
