### ISSUE TITLE
About The Logia Invulnerability Option

### ISSUE THREAD

**Issue by Sogekeeper** [Wynd/MineMineNoMi3#58]
Is it possible to make an option in the cfg file for logia users to take reduced damage? When playing **_solo_** I don't want to be invulnerable because it's too easy, but I also want something for the roleplay, to feel like logia fruits are "better". Maybe just a resistance buff that never wears off, with that all mobs from all mods can kill you but not so fast. 
![image](https://user-images.githubusercontent.com/46176324/50462979-f18bc680-096f-11e9-968d-4507f90cbfae.png)

**Comment by Wynd** [comment]
tl;dr it's gonna be a 'no' for now...since there are a lot of other things to work on...for the "easy" aspect of the post you shouldn't worry too much about that for longer, once the DF update will be done I'll add _a fuck ton_ of new mobs...some of which with kairoseki items or haki, that should give ya'll a challenge.

For future tho, I might consider adding this as a side feature just like with the stats values after death option.
