### ISSUE TITLE
Please buff some dfs

### ISSUE THREAD

**Issue by AdmiralSakazuki** [Wynd/MineMineNoMi3#65]
I want to suggest to buff some devil fruits like bane bane or bari bari because attacking with them is kinda difficult especially with bari bari which it only has 2 moves that deal dmg and one of them only deals 10 hearts and against other players that have a lot of doriki and have like 40 hearts its kinda hard to get close to them and use that move also I think that bane bane is ok but it can be better also you guys should also add more zoans xd we only have 2 and both of them are pretty good ushi ushi is actually pretty good for combos and tori tori is just OP cuz of flight heal and op dmg xd

**Comment by FGpisces** [comment]
Hi, we'll try to balance all DFs like they should be in the following versions, but some DFs will obviously still be stronger. People with "weaker" DFs will just have to find better ways to use them.
We'll also add a lot more Zoans as time comes, but not at once, because Zoans usually take the most work.
