### ISSUE TITLE
some suggestions for the mod

### ISSUE THREAD

**Issue by MXlordsMapone123** [Wynd/MineMineNoMi3#74]
-third person busoshoku haki view
-crafting game items
-villages with mod's own NPCs that can sell mod items
-anime places that will be generated in the world of minecraft
-enable and disable logia intangibility
-more zoans
-fruit spawn randomly
-3d models for fruits
-sky islands
-bosses
-kurozu attack for yami
-awakening mode for fruits
-Amaru mode for goro
-when gear fourth is activated appear the busoshoku haki in the hands and feet of the players and a smoke
-I really want you to add to the katakuri mochi mochi fruit and my favorite
-different skills for each game sword
-to be able to use the powers of gura gura together with the bisento
-some means of locomotion at sea
-- thanks for being dedicated in this mod I want this mod to be the best op mod for minecraft

**Comment by FGpisces** [comment]
Hi.
First of all, not to be rude, but these are definitely NOT suggestions. These are such obvious things that we don't even need to put them on our to-do lists, and they aren't even suggestions, because they're just "statements". A suggestion is when you properly explain how we should add it, explain it thoroughly, and MOST IMPORTANT, say how it should worn in Minecraft.
We already have detailed plans for most things to come, and are happy for new suggestions, but "more zoans" is NOT a suggestion, it's the natural order of things, of course we're gonna add more zoans, we'll add them when we finish them. 
Among other things, it's already possible to change logia intangibility in the config.
Don't take it personally, but if people want to give us suggestions, this is nowhere near a suggestion.

**Comment by MXlordsMapone123** [comment]
you're right I'll soon have a suggestion for the most thoughtful gura
