### ISSUE TITLE
Yami Yami no Mi bug

### ISSUE THREAD

**Issue by Cheese4Every1** [Wynd/MineMineNoMi3#83]
**Describe the bug**
When a player eats a different Logia fruit and later eats the Yami Yami no Mi, they lose the Logia invulnerability that comes with the first fruit. This does not happen when the Yami Yami no Mi is eaten first followed by the second Logia.

**To Reproduce**
1. Eat a Logia fruit other than Yami Yami no Mi (Moku Moku no Mi, for instance)
2. Allow a mob to hit you to confirm you have logia invulnerability
3. Eat the Yami Yami no Mi
4. Allow a mob to hit you again, you will find you do not have Logia Invulnerability anymore.

**Expected behavior**
Since all other features of the first Logia are retained when you eat the Yami Yami no Mi second, I expected the Logia invulnerability to also remain active. 

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Wynd** [comment]
That is normal...to some degree...If we go super in depth...you shouldn't be able to eat yami yami after another fruit, however we allow for this and thus after you eat yami it becomes your "main fruit"..as such you lose the logia invulnerability of the first fruit that now becomes the "secondary fruit"

(However we hardly know anything about this ability...so it might not even be because of one yami yami's abilities...idk)

But thanks for using the format and for write a very on-point report <3

**Comment by Wynd** [comment]
Fixed in 0.5.0
